name: deeplab-pytorch
dependencies:
  - click
  - conda-forge::pydensecrf
  - cudatoolkit=11.3 #or 10.2 where under RTX 30X0 GPU
  - matplotlib
  - python=3.6
  - pytorch::pytorch>1.2.0
  - pytorch::torchvision
  - pyyaml
  - scipy
  - tqdm
  - pip:
    - addict
    - black
    - joblib
    - omegaconf
    - opencv-python
    - tensorflow
    - torchnet
